frase = str(input("Digite algo: "))
print('O tipo primitivo desse valor é {}' .format(type(frase)))
print('Só tem espaços? {}' .format(frase.isspace()))
print('É um número? {}' .format(frase.isnumeric()))
print('É alfabético? {}' .format(frase.isalpha()))
print('É alfanumérico? {}' .format(frase.isalnum()))
print('Está em maiúsculas? {}' .format(frase.isupper()))
print('Está em minúsculas? {}' .format(frase.islower()))
print('Está capitalizada? {}' .format(frase.istitle()))